In [1]:
import numpy as np

In [3]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
np.array([1,2,3], ndmin=2)

array([[1, 2, 3]])

In [37]:
dt = np.dtype([('name', np.str), ('age', np.int8), ('habbit', np.str)])
M = np.array([('zys', 18, 'test'), ('zys1', 16, 'test2')])
print(M)

[['zys' '18' 'test']
 ['zys1' '16' 'test2']]


In [48]:
np.arange(24).reshape(2, 4, 3).flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [70]:
# 创建10x2的空数组，元素为随机值，因为他们未初始化
#np.empty((10,2), dtype=np.int8)
np.empty((10,2), dtype=int)

array([[ 1152921504606846976, -5764598737309611811],
       [                  15,                    0],
       [                   0,                    0],
       [                   0,                    0],
       [                   0,                    0],
       [                   0,                    0],
       [                   0,                    0],
       [                   0,  7022275352057965921],
       [ 1152921504606846976,  2305851794938316362],
       [                   7,                    0]])

In [74]:
# 创建10x2的0填充的数组
np.zeros((10,2), dtype=float, order='C')

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [87]:
np.frombuffer(b"hello", dtype='S1')

array([b'h', b'e', b'l', b'l', b'o'], dtype='|S1')

In [92]:
np.fromiter(iter(range(5)), dtype=float)

array([0., 1., 2., 3., 4.])

In [100]:
np.arange(1,5, dtype=float)

array([1., 2., 3., 4.])

In [108]:
# 等差数组
np.linspace(1,20,10, dtype=float, endpoint=False)

array([ 1. ,  2.9,  4.8,  6.7,  8.6, 10.5, 12.4, 14.3, 16.2, 18.1])

In [119]:
# 等比数列
np.logspace(0, 9, 10, base=2, dtype='i2')
np.logspace(0, 9, 10, base=2, dtype=int)
np.logspace(0, 9, 10, base=2, dtype=np.int)
np.logspace(0, 9, 10, base=2, dtype=np.int8)

array([   1,    2,    4,    8,   16,   32,   64, -128,    0,    0],
      dtype=int8)

In [123]:
# numpy支持用内置的 slice 做切割 
v = np.arange(10)
print(v)
v[2:7:2]

[0 1 2 3 4 5 6 7 8 9]


array([2, 4, 6])

In [148]:
# 多维数组切割练习
#M = np.random.randint(100, size=(20, 5))
#print(M)
#print('-------->slice')
#print(M[:,1:5])

In [149]:
# 获取数组中(0, 0) (1, 1) (2, 0)的位置的元素
x = np.array([[1,  2],  [3,  4],  [5,  6]]) 
y = x[(0, 1, 2), (0, 1, 0)]
print(y)

[1 4 5]


In [194]:
x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])  
print ('我们的数组是：' )
print (x)
print ('\n')
#x[:,[0,1]]
#x[[0,2],:]
#x[[0,2],:]

#index = list(range(0,4,2))
#x[index,:]

np.sum(x > 5)

我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]




6

In [199]:
# 花式索引
x=np.arange(32).reshape((8,4))
print(x)
print('-------')
#print (x[[4,2,1,7]])
print (x[[-4,-2,-1,-7]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
-------
[[16 17 18 19]
 [24 25 26 27]
 [28 29 30 31]
 [ 4  5  6  7]]


In [204]:
# 花里胡哨 索引增强版, 入多个索引数组（要使用np.ix_）
print(x[[0,1]])
print('----')
print(x[np.ix_([0,1])])
print('----')
print(x[np.ix_([0,1], [0,3,2,1])])

[[0 1 2 3]
 [4 5 6 7]]
----
[[0 1 2 3]
 [4 5 6 7]]
----
[[0 3 2 1]
 [4 7 6 5]]


In [209]:
# numpy 计算，必须是两个矩阵的维度相同
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
print(a*b)

[ 10  40  90 160]


In [213]:
#当运算中的 2 个数组的形状不同时，numpy 将自动触发 "广播机制" 。如：
#简单理解：-> *** 数组拥有相同形状。

a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([1,2,3])
print(a + b)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


%% html
<img src="img/numpy1.png" />

In [230]:
# 遍历矩阵元素, np.nditer()
a = np.arange(6).reshape(2,3)
print ('原始数组是：')
print (a)
print ('\n')
print ('迭代输出元素：')
# 如果要修改元素的值，需要制定option_flats = write
for i in np.nditer(a, op_flags=['readwrite']):
    i[...] = 2 * i
print(a)

原始数组是：
[[0 1 2]
 [3 4 5]]


迭代输出元素：
[[ 0  2  4]
 [ 6  8 10]]


In [244]:
# 迭代器遍历对应于每列，并组合为一维数组。
import numpy as np 
a = np.arange(0,60,5) 
a = a.reshape(3,4)  
print ('原始数组是：')
print (a)
print ('\n')
print ('修改后的数组是：')
for i in np.nditer(a, flags=['external_loop'], order='F'):
    print(i, end=",")
print('\n----\n')
print(a.T)
print('\n----\n')
#print(a.copy(order="F"))

原始数组是：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


修改后的数组是：
[ 0 20 40],[ 5 25 45],[10 30 50],[15 35 55],
----

[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]

----



In [246]:
# 广播迭代
# 如果两个数组是可广播的，nditer 组合对象能够同时迭代它们。 
# 假设数组 a 的维度为 3X4，数组 b 的维度为 1X4 ，则使用以下迭代器（数组 b 被广播到 a 的大小）。
import numpy as np 
 
a = np.arange(0,60,5) 
a = a.reshape(3,4)  
print  ('第一个数组为：')
print (a)
print  ('\n')
print ('第二个数组为：')
b = np.array([1,  2,  3,  4], dtype =  int)  
print (b)
print ('\n')
print ('修改后的数组为：')
for x,y in np.nditer([a,b]):  
    print ("%d:%d"  %  (x,y), end=", " )

第一个数组为：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


第二个数组为：
[1 2 3 4]


修改后的数组为：
0:1, 5:2, 10:3, 15:4, 20:1, 25:2, 30:3, 35:4, 40:1, 45:2, 50:3, 55:4, 

In [261]:
# 迭代数组
import numpy as np
 
a = np.arange(9).reshape(1, 1, 3,3) 
print ('原始数组：')
for row in a:
    print (row)
 
#对数组中每个元素都进行处理，可以使用flat属性，该属性是一个数组元素迭代器：
print ('迭代后的数组：')
for element in a.flat:
    print (element)

# flatten 返回一份数组拷贝，对拷贝所做的修改不会影响原始数组
print(a.flatten(order="F")) # 按照fortune风格（列），遍历并且 放平 矩阵
print(np.ravel(a, order="F")) #这个方法也可以放平，但是会影响原始数组

原始数组：
[[[0 1 2]
  [3 4 5]
  [6 7 8]]]
迭代后的数组：
0
1
2
3
4
5
6
7
8
[0 3 6 1 4 7 2 5 8]
[0 3 6 1 4 7 2 5 8]


In [266]:
# 颠倒矩阵
import numpy as np
 
a = np.arange(12).reshape(3,4)
 
print ('原数组：')
print (a )
print ('\n')
print('翻转')
print(np.transpose(a))
print ('\n')
print('转置矩阵')
print(a.T)
print ('\n')

原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


翻转
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


转置矩阵
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]




In [281]:
# 堆叠数组
import numpy as np
 
a = np.array([[1,2],[3,4]])
 
print ('第一个数组：')
print (a)
print ('\n')
b = np.array([[5,6],[7,8]])
 
print ('第二个数组：')
print (b)
print ('\n')
print ('stack')
print(np.stack((a, b), 0))
print ('\n')
print ('concatenate')
print(np.concatenate((a, b)))
print ('\n')
print ('vstack')
print(np.vstack((a, b)))
print ('\n')
print ('hstack')
print(np.hstack((a, b)))

第一个数组：
[[1 2]
 [3 4]]


第二个数组：
[[5 6]
 [7 8]]


stack
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


concatenate
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


vstack
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


hstack
[[1 2 5 6]
 [3 4 7 8]]


In [284]:
import numpy as np
 
a = np.arange(9)
 
print ('第一个数组：')
print (a)
print ('\n')
print(np.split(a, 3))
print(np.split(a, [4,7]))

第一个数组：
[0 1 2 3 4 5 6 7 8]


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [298]:
a = np.arange(9).reshape(3, 3)
print('原 \n', a)
print('\n hsplit')
print(np.hsplit(a,3))
print('\n vsplit')
print(np.vsplit(a,3))

原 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

 hsplit
[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]

 vsplit
[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]


In [320]:
# 添加元素,如果不指定轴，会被展开
a = np.array([[1,2,3],[4,5,6]])
 
print ('第一个数组：')
print (a)
print ('\n')
#print(np.append(a, [3,3,3]))
print(np.append(a, [[3,3,3]], axis=0))
print ('\n')
print ('沿轴 1 添加元素：')
print (np.append(a, [[5,5,5],[7,8,9]],axis = 1))
print ('插入元素：')
#print (np.insert(a, 1, [5,5,5]))
print (np.insert(a, 1, [5,5,5], axis=0))
print ('删除元素：')
print (np.delete(a, 1, axis=0))

第一个数组：
[[1 2 3]
 [4 5 6]]


[[1 2 3]
 [4 5 6]
 [3 3 3]]


沿轴 1 添加元素：
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]
插入元素：
[[1 2 3]
 [5 5 5]
 [4 5 6]]
删除元素：
[[1 2 3]]


In [327]:
# 去重
a = np.array([5,2,6,2,7,5,6,8,2,9])
print ('第一个数组：')
print (a)
print ('\n')
 
print ('第一个数组的去重值(像set)：')
print(np.unique(a))

print ('去重数组的索引数组：')
u,indices = np.unique(a, return_index = True)
print (u, indices)
print ('\n')

print ('返回去重元素的重复数量：')
u,indices = np.unique(a,return_counts = True)
print (u)
print (indices)



第一个数组：
[5 2 6 2 7 5 6 8 2 9]


第一个数组的去重值(像set)：
[2 5 6 7 8 9]
去重数组的索引数组：
[2 5 6 7 8 9] [1 0 2 4 7 9]


返回去重元素的重复数量：
[2 5 6 7 8 9]
[3 2 2 1 1 1]
