In [27]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

In [30]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [31]:
X[:3,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [32]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state = 666)

In [33]:
X_train[:3, :]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [5.7, 2.8, 4.1, 1.3]])

In [35]:
standardScaler = StandardScaler()
standardScaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [36]:
# normalize,根据4个特征，算出的均值
standardScaler.mean_

array([5.83416667, 3.08666667, 3.70833333, 1.17      ])

In [37]:
# normalize,根据4个特征，算出的方差
standardScaler.scale_

array([0.81019502, 0.44327067, 1.76401924, 0.75317107])

In [38]:
# 此时已经是X_train归一化的结果
X_train = standardScaler.transform(X_train)
X_test_standard = standardScaler.transform(X_test)
X_train[:3,:]

array([[-0.90616043,  0.93246262, -1.30856471, -1.28788802],
       [-1.15301457, -0.19551636, -1.30856471, -1.28788802],
       [-0.16559799, -0.64670795,  0.22203084,  0.17260355]])

In [41]:
knn_clf = KNeighborsClassifier(n_neighbors=3)
knn_clf.fit(X_train, y_train)
knn_clf.score(X_test_standard, y_test)

1.0

In [57]:
np.array([[1,2],[1,2],[2,2]]).shape[1]

2