In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [3]:
iris = datasets.load_iris()

In [4]:
X = iris.data
y = iris.target

In [7]:
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [11]:
### train_test_split
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
### 随机抽取y的index

In [19]:
# 打乱索引,打乱y的结果集的索引
shuffle_indexes = np.random.permutation(len(X))
shuffle_indexes

array([ 44,  82,  57,  89,  54,  16,   2, 104,  88,  17,  63,  60, 105,
       119,  10,  94, 117,  85,  99,  28,   9,  30,  14,  38,  32,   1,
        61,  21,  31,  65,  55,  87,  51,  64, 141, 131,  48, 136, 100,
        34,  86,  84,  18,  41, 149,  24,  46,  96,  97, 121,  79, 142,
        56,  50, 125,  12,  93, 106,  72,  52,  20,  33,  11, 109,  47,
        77, 107, 134, 123,  27, 118, 126,  76, 137, 110,  29,  36,  39,
       108,  59,  42, 139,  74,   4, 112,  71,   0, 113, 120, 135,  73,
       101,  58, 111,  66,  75,   8, 102,  23,  95,  45,  35,  92,  62,
        25,  43,  68, 127, 140, 145,  67,  53,  69, 132,  26,  15, 147,
       130, 103,   7,   3, 114, 148,  91, 133,  49,  40, 124, 116,  19,
        80,  13, 144,  98,  83,   5,  22,  78,  90,  81, 115, 129,  70,
       122, 143,  37, 138, 128,   6, 146])

In [22]:
# 分出20 测试集， 80训练集
test_size = int(len(X) * .2)
test_indexes = shuffle_indexes[:test_size]
train_indexes = shuffle_indexes[test_size:]

In [23]:
# funncy indexing , 用随机数80%+20%下标拿 训练集和测试集
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [31]:
# 120 * 4 矩阵的结果是 y
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [41]:
### 将 分测试集 训练集 的方法封装
def train_test_split(X, y, test_ratio=0.2, seed=None):
    assert X.shape[0] == y.shape[0]
    assert 0.0 <= test_ratio <= 1.0
    
    if seed:
        np.random.seed(seed)

    shuffle_indexes = np.random.permutation(len(X))
    test_size = int(len(X) * test_ratio)
    test_indexes = shuffle_indexes[:test_size]
    train_indexes = shuffle_indexes[test_size:]
    X_test = X[test_indexes]
    y_test = y[test_indexes]
    X_train = X[train_indexes]
    y_train = y[train_indexes]
    return X_train, X_test, y_train, y_test

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [56]:
%run knn/knn_classify.py

In [57]:
my_knn_clf = KNNClassifier(k=3)
my_knn_clf.fit(X_train, y_train)

KNN(k=3)

In [59]:
y_predict = my_knn_clf.predict(X_test)
y_predict

array([2, 0, 0, 1, 2, 1, 1, 1, 1, 2, 1, 1, 0, 1, 0, 0, 0, 2, 0, 2, 0, 1,
       0, 0, 0, 1, 2, 2, 2, 0])

In [60]:
y_test

array([2, 0, 0, 1, 2, 1, 1, 1, 1, 2, 1, 1, 0, 1, 0, 0, 0, 2, 0, 2, 0, 1,
       0, 0, 0, 1, 2, 1, 2, 0])

In [71]:
#准确率
#list((y_predict == y_test)).count(True) / len(y_test)
sum(y_predict == y_test) / len(y_test)

0.9666666666666667

In [76]:
# sklearn 中的 train_test_split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)
