In [359]:
p = print
import numpy as np
np.__version__

'1.17.0'

In [4]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
L[5]

5

In [12]:
L[5] = "testtt"
L

[0, 1, 2, 3, 4, 'testtt', 6, 7, 8, 9]

### python list 可以存各种类型，效率低

In [14]:
import array
arr = array.array('i', [i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[5] = 140
arr

array('i', [0, 1, 2, 3, 4, 140, 6, 7, 8, 9])

In [18]:
# int array  不能赋值 string！！！ arr[5] = 'test'

In [20]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [27]:
#nparr 也不能赋值字符串 ！！！ nparr[5] = 'test'

In [29]:
nparr.dtype

dtype('int64')

In [35]:
nparr[5] = 5.0 # 隐士类型转换
nparr[3] = 3.14
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
nparr2 = np.array([], dtype=float)
nparr2.dtype

dtype('float64')

In [51]:
# 创建0的np数组
np.zeros(10)
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [56]:
np.zeros(shape=(3,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [66]:
np.ones(shape=(3, 5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [73]:
np.full((4,5), fill_value=66.6)

array([[66.6, 66.6, 66.6, 66.6, 66.6],
       [66.6, 66.6, 66.6, 66.6, 66.6],
       [66.6, 66.6, 66.6, 66.6, 66.6],
       [66.6, 66.6, 66.6, 66.6, 66.6]])

In [83]:
# arange , 传统的步长不能为0.2浮点数
list(range(0, 20, 2))
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [88]:
np.arange(0, 20, 2)
np.arange(0, 20, 0.9)

array([ 0. ,  0.9,  1.8,  2.7,  3.6,  4.5,  5.4,  6.3,  7.2,  8.1,  9. ,
        9.9, 10.8, 11.7, 12.6, 13.5, 14.4, 15.3, 16.2, 17.1, 18. , 18.9,
       19.8])

In [94]:
# 等差数列 0 - 20 步长 2 有 11 个点
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [146]:
### random
print('random : ', np.random.randint(0, 10))
np.random.randint(0, 10, size=3)

random :  6


array([5, 7, 7])

In [162]:
# seed 相同，随机值不会变
np.random.seed(42)
np.random.randint(4, 8, size=(2, 2))

array([[6, 7],
       [4, 6]])

In [161]:
np.random.seed(42)
np.random.randint(4, 8, size=(2, 2))

array([[6, 7],
       [4, 6]])

In [170]:
np.random.random(size=(2, 2))

array([[0.9093204 , 0.25877998],
       [0.66252228, 0.31171108]])

In [250]:
# 生成均值 10 ,方差100的随机数
np.random.normal(10, 100)
np.random.normal(10, size=(2, 2))

array([[11.04934739, 11.32510566],
       [10.73450106,  9.04550274]])

In [252]:
np.random.normal?

In [254]:
# numpy的基础操作， reshape等
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [257]:
X = np.arange(15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [266]:
print(x.ndim)
print(X.ndim)
print(x.shape, X.shape)
print(x.size, X.size)

1
2
(10,) (3, 5)
10 15


In [284]:
### numpy.array的数据访问
X[0][4] == X[0, 4]
X[(2, 2)] == X[2, 2] # 简写

True

In [294]:
X[:, ::-1]
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [324]:
X[:, 2:]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [326]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [331]:
subX[0, 0] = 100
subX ### 对于np，切片不会创建拷贝，所以修改”子矩阵“，”原矩阵“也会被改（指针引用）

array([[100,   1,   2],
       [  5,   6,   7]])

In [332]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [341]:
subX = X[:2, :3].copy() # 真副本
subX[0] = 200
print(X, '\n\n',subX)

[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]] 

 [[200 200 200]
 [  5   6   7]]


In [352]:
# reshape
x.shape
x.ndim
A = x.reshape(2, 5)
print(A,'\n--\n' ,x)

[[0 1 2 3 4]
 [5 6 7 8 9]] 
--
 [0 1 2 3 4 5 6 7 8 9]


In [362]:
p(x.ndim)
p(x.reshape(1, 10).ndim)

1
2


In [367]:
x.reshape(10, -1) # 希望有10行，每行不管多少个，缺省值 写 -1

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [373]:
x.reshape(2, -1) # -1 是缺省值， 我只要2行，每行几个我不管

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [374]:
# 合并操作

In [376]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [382]:
np.concatenate([x, y, [666] * 3])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [383]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

In [388]:
np.concatenate([A, A, [[6,6,6], [6,7,8]]])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [6, 6, 6],
       [6, 7, 8]])

In [390]:
np.concatenate([A, A], axis=1) # axis（轴），0 是横着往上粘， 1 是横着往左粘

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [393]:
z = np.array([666, 666, 666])
z

array([666, 666, 666])

In [405]:
# 这三种合并写法结果一样
np.concatenate([A, [z]])
np.concatenate([A, z.reshape(1, -1)])
np.vstack([A, z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [417]:
B = np.full((2, 2), 100)
B

array([[100, 100],
       [100, 100]])

In [420]:
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [422]:
### 分割
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [428]:
np.split(x, [3, 7]) # 0,1,2   3,4,5,6  7,8,9

[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [429]:
np.split(x, [5])

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [432]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [434]:
np.split(A, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [436]:
np.split(A, [2], axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [440]:
upper, lower = np.vsplit(A, [2])
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [442]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [444]:
left, right = np.hsplit(A, [2])
print(left, '\n' * 3, right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 


 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [448]:
x, y = np.hsplit(A, [-1])
p(x, '\n' * 2, y)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]] 

 [[ 3]
 [ 7]
 [11]
 [15]]


In [451]:
y[:, 0]

array([ 3,  7, 11, 15])

In [461]:
# numpy 向量计算
%time
L = np.arange(10)
L * 2

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 8.82 µs


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [463]:
X = np.arange(1, 16).reshape((3, 5))
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [473]:
1 / X

array([[0.33333333, 0.25      , 0.2       , 0.16666667, 0.14285714],
       [0.125     , 0.11111111, 0.1       , 0.09090909, 0.08333333],
       [0.07692308, 0.07142857, 0.06666667, 0.0625    , 0.05882353]])

In [480]:
np.tan(X)

array([[-1.42546543e-01,  1.15782128e+00, -3.38051501e+00,
        -2.91006191e-01,  8.71447983e-01],
       [-6.79971146e+00, -4.52315659e-01,  6.48360827e-01,
        -2.25950846e+02, -6.35859929e-01],
       [ 4.63021133e-01,  7.24460662e+00, -8.55993401e-01,
         3.00632242e-01,  3.49391565e+00]])

In [482]:
np.exp(X)

array([[2.00855369e+01, 5.45981500e+01, 1.48413159e+02, 4.03428793e+02,
        1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
        1.62754791e+05],
       [4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
        2.41549528e+07]])

In [485]:
3**X

array([[       27,        81,       243,       729,      2187],
       [     6561,     19683,     59049,    177147,    531441],
       [  1594323,   4782969,  14348907,  43046721, 129140163]])

In [487]:
np.log(X)

array([[1.09861229, 1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527, 2.48490665],
       [2.56494936, 2.63905733, 2.7080502 , 2.77258872, 2.83321334]])

In [489]:
np.log10(X)

array([[0.47712125, 0.60205999, 0.69897   , 0.77815125, 0.84509804],
       [0.90308999, 0.95424251, 1.        , 1.04139269, 1.07918125],
       [1.11394335, 1.14612804, 1.17609126, 1.20411998, 1.23044892]])

In [492]:
A = np.arange(4).reshape(2, 2)
B = np.full((2, 2), 10)
print(A, '\n'* 2, B)

[[0 1]
 [2 3]] 

 [[10 10]
 [10 10]]


In [495]:
A + B
A - B

array([[-10,  -9],
       [ -8,  -7]])

In [497]:
A * B

array([[ 0, 10],
       [20, 30]])

In [499]:
A / B

array([[0. , 0.1],
       [0.2, 0.3]])

In [504]:
A.dot(B)

array([[10, 10],
       [50, 50]])

In [510]:
np.arange(6).reshape(2, 3).T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [514]:
# 向量和矩阵的运算
v = np.array([1, 2])
m = np.arange(4).reshape(2, 2)
p(v, '\n'*2 ,m)

[1 2] 

 [[0 1]
 [2 3]]


In [532]:
#简写
v + m == [v] * A.shape[0] + m

array([[ True,  True],
       [ True,  True]])

In [533]:
np.tile(v, [2, 1]) # 也可以堆叠

array([[1, 2],
       [1, 2]])

In [535]:
v.dot(A)

array([4, 7])

In [540]:
A ### A的逆矩阵

array([[0, 1],
       [2, 3]])

In [545]:
invA = np.linalg.inv(A)

In [547]:
invA.dot(A)

array([[1., 0.],
       [0., 1.]])

In [553]:
M = np.arange(16).reshape(2, -1)
N = np.linalg.pinv(M) #伪逆矩阵

array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17]])